### ISSUE TITLE
Can't use both yaml and oyaml at the same time

### ISSUE THREAD

**Issue by Shreeyak** [wimglenn/oyaml#15]
If I import oyaml and yaml at the same time, using yaml lib returns orderedDicts!

Example here. First I open an interactive shell and import yaml, use it to load a file. It returns a dict as expected. Then I import oyaml and run the SAME code as above, using YAML not oyaml and it returns an ordered dict!

In my script, simply writing `import oyaml` at the top, changes the functionality of every `yaml.load` command in the script!

How can I cause these 2 libs to not clash?

```
>>> import yaml
>>> with open('config/config.yaml') as f:
...   config_yaml = yaml.safe_load(f)
... 
>>> config_yaml
{'train': {'datasets': [{'images': ..............


>>> import oyaml
>>> with open('config/config.yaml') as f:
...   config_yaml = yaml.safe_load(f)
... 
>>> config_yaml
OrderedDict([('train', OrderedDict([('datasets', [OrderedDict([('images', ...........
```

**Comment by wimglenn** [comment]
Hi @Shreeyak, that's correct: `oyaml` is intended to modify the behavior of `pyyaml` to provide a different default behavior with regards to preservation of ordering in mappings. It's a monkeypatch of `pyyaml`, by design, and this won't be changing.

If you want a default loader/dumper and an ordered loader separately, then this is not the library for you. Look instead at another library, for example https://github.com/Phynix/yamlloader

**Comment by Shreeyak** [comment]
Ah, I see. Thank you for clarifying!

**Comment by wolfgang-noichl** [comment]
It's kinda worse than that (python2.7, not sure if there are similar problems on python3):
```python
import yaml
import other_dependency  # contains import oyaml

type(yaml.load("{xy: 'z'}"))  # -> OrderedDict!
```
This is a bit hard to debug, since you actually need to know whether  _your dependencies_ (entirely different namespaces) ever import `oyaml`.

**Comment by wimglenn** [comment]
@wolfgang-noichl  As already mentioned, that is the intention - to modify the global behavior of `pyyaml` itself. Note that a standard dict is returned when possible (CPython >= 3.6 and Python >= 3.7). Given that `OrderedDict` is a `dict` subclass, what problem are you actually trying to debug?

**Comment by wolfgang-noichl** [comment]
What I'm trying to say is whatever slightly different behavior `oyaml` has compared to `pyyaml`, the way this is done right now monkey patches it in entirely different places and namespaces. That wasn't what I expected from an `import`, and neither from the readme. The resulting bugs can be quite hard to spot, because you might not even be aware that an unused part of a dependency imports oyaml.

I totally agree that there is not much margin for different behaviour, but nevertheless...

Here's the actual bug (fixed by `isinstance`, so I don't have strong opinions on whether you accept the PR or not :wink:):

```python
# file_a.py
import oyaml

def func():
[...]

# file_b.py
import yaml
from file_a import func

x = yaml.load(...)
if type(x['y']) == dict:
[...]
```

**Comment by wimglenn** [comment]
That seems too contrived to call a bug, because Python developers don’t (or shouldn’t) type check using equality comparisons. Mostly don’t type check at all.. 🦆
